### ISSUE TITLE
VWF Messages patch no longer works with the latest SA-1 PACK

### ISSUE THREAD

**Issue by Knucklesfan** [VitorVilela7/SA1-Pack#11]
The latest version of rpg hacker's VWF messages causes the latest SA-1 pack to crash SMW. Previous versions worked just fine with VWF messages, but not Lm300, so downgrading isn't an option. Any help would be greatly appreciated!

**Comment by TheLX5** [comment]
Try using the zip that I attached [here](https://github.com/RPGHacker/SMW-Workspace/issues/19#issuecomment-466524106). It never got a proper release either in GitHub or the SMWC patches section. 

Yoshifanatic is working on adding new features to the patch (and fixing this issue), but I have no idea how stable or how finished is his version at this moment. He kinda tends to disappear very often.

**Comment by VitorVilela7** [comment]
Since SA-1 Pack v1.30, it replaces the SMW IRQ system with its own system, which VWF dialogues attempts hijacking it and does not work correctly.

Try using LX5's solution but definitely I will need to rethink the system to not cause so much trouble with patches like that one.

**Comment by Knucklesfan** [comment]
Thanks for the help guys, definitely saved my hack!

**Comment by VitorVilela7** [comment]
If you need anything let me know!
