### ISSUE TITLE
Feature Request - Sethbling SMW Jail Break

### ISSUE THREAD

**Issue by amoore2600** [VitorVilela7/SA1-Pack#17]
Please make the SA1-Pack for Super Mario World compatible with the Seth Bling Jail Break. I have included the youtube video demo and a link to a Jailbreak SRAM file.    

The Jail break suffers majorly from slow down and seems like it could greatly benefit from the SA-1 Pack.   

Please close this Issue if feature request are not allowed or accepted.

https://www.youtube.com/watch?v=Ixu8tn__91E

https://www.youtube.com/redirect?q=https%3A%2F%2Fsethbling.s3-us-west-2.amazonaws.com%2FDownloads%2FBizhawk%2BScripts%2FSMWJailbreak.SaveRAM&event=video_description&redir_token=XjtgNKGe7UVPKVDrZtKlxVTEN5l8MTU3MTUxNjQ1OEAxNTcxNDMwMDU4&v=Ixu8tn__91E

**Comment by VitorVilela7** [comment]
SMW SA-1 Pack modifies most of the SMW engine and therefore it's impossible to make that jailbreak SRAM hack compatible with SA-1 without rewriting his jailbreak code from scratch. The SRAM layout is completely different on SA-1 Pack (BW-RAM). You will have to ask him for making a SA-1 compatible version of it, pretty much like all other SMW resources that does not work with SA-1.
