### ISSUE TITLE
IRQ-as-NMI issues

### ISSUE THREAD

**Issue by TheLX5** [VitorVilela7/SA1-Pack#19]
If IRQ-as-NMI is activated, code that runs way too early in the NMI routine (CC-DMA upload to VRAM, DSX integration, UberASMTool's NMI code), will fail to update on the screen. 
This is easily seen when placing a [dynamic sprite](https://www.smwcentral.net/?p=section&a=details&id=13945) on a level, which ends up being displayed like [this](https://cdn.discordapp.com/attachments/624113770775707678/719481607676756078/unknown.png) since DSX code runs quite early in SA-1 Pack 1.32 and the current master branch.

The code I utilized to enable IRQ-as-NMI on UberASMTool's level init code is:
```
!_scanlines = $02
	lda.b #%00000001
	sta $1D00
	lda.b #$E0-!_scanlines
	sta $1D01
	jsr $1D08
```
By setting up a breakpoint on bsnes-plus to detect the dynamic sprite on a level, it shows that the NMI code is being run earlier than it should (V-Count is lower than the usual value), so the system is working as intended. Maybe I hit an actual SNES limitation where you can't update the VRAM at a lower V-Count? Snes9x 1.60 and bsnes v114 have this issue and I doubt it's going to be different on actual hardware. Or perhaps I forgot to set up something else? $1D08 already setups the IRQ trigger stuff, so I have no idea what could it be.

**Comment by VitorVilela7** [comment]
Have you checked if forced-blank is enabled? Some patches tend to remove
the LDA #$80 : STA $2100 code inappropriately.

Em seg., 8 de jun. de 2020 às 06:33, TheLX5 <notifications@github.com>
escreveu:

**Comment by TheLX5** [comment]
Would HDMA setting $2100 work in this case or do I need to strictly enable F-Blank with code as early as possible during the NMI routine?

**Comment by VitorVilela7** [comment]
Yes, but don't forget that you must enable F-Blank on the previous scanline
if you're doing via HDMA.

IRQ-as-NMI fires around H=2..6 while HDMA runs at H=260 +- so you should
run it one scanline before in case you're using IRQ-as-NMI.

Em seg., 8 de jun. de 2020 às 15:19, TheLX5 <notifications@github.com>
escreveu:

**Comment by TheLX5** [comment]
Yup, I got it to work perfectly.

```
!fblank_ram = $35FF
!_scanlines = $0B

	lda #$80
	sta !fblank_ram
	lda.b #%00000001
	sta $1D00
	lda.b #$E0-!_scanlines
	sta $1D01
	jsr $1D08

	rep #$20
	lda #$0040
	sta $4370
	lda.w #.table
	sta $4372
	sep #$20
	lda.b #.table/$10000
	sta $4374
	lda.b #$00
	sta $4377

	lda #$80
	tsb $0D9F|!addr

	rtl
.table
	db !_scanlines : dw !fblank_ram
	db ($E0-(!_scanlines*2))/2 : dw $0DAE|!addr
	db (($E0-(!_scanlines*2))/2)-1 : dw $0DAE|!addr
	db !_scanlines+1 : dw !fblank_ram
	db $00
```

I knew I was missing something crucial. I guess that's what I get for not messing with ASM for a few months.

Thanks!
